#!/usr/bin/env bash
# Scaffold a new Project Euler problem package and register it.
#
#   ./newprob.sh 7        -> creates p007/{p007.go,p007_test.go,run.go}
#   ./newprob.sh --sync   -> only regenerate problems.go and check registrations
#
# problems.go is always regenerated from the pNNN directories on disk, and every
# run.go is checked to make sure it registers the number its directory claims.
set -euo pipefail

cd "$(dirname "$0")"
module=$(awk '/^module /{print $2}' go.mod)

usage() { echo "usage: $0 <problem-number> | --sync" >&2; exit 1; }
[[ $# -eq 1 ]] || usage

if [[ $1 != --sync ]]; then
	[[ $1 =~ ^[0-9]+$ ]] || usage
	n=$((10#$1))
	((n > 0)) || usage
	pkg=$(printf 'p%03d' "$n")

	if [[ -e $pkg ]]; then
		echo "error: $pkg already exists" >&2
		exit 1
	fi
	mkdir "$pkg"

	cat >"$pkg/$pkg.go" <<EOF
package $pkg

func Solve(limit int) uint64 {
	// TODO: solve problem $n
	return 0
}
EOF

	cat >"$pkg/${pkg}_test.go" <<EOF
package $pkg

import "testing"

func TestSolve(t *testing.T) {
	tests := []struct {
		name  string
		limit int
		want  uint64
	}{
		// TODO: add the example from the problem statement and the real answer.
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := Solve(tt.limit)
			if got != tt.want {
				t.Errorf("Solve(%d) = %d; want %d", tt.limit, got, tt.want)
			}
		})
	}
}

func BenchmarkSolve(b *testing.B) {
	for b.Loop() {
		_ = Solve(0)
	}
}
EOF

	cat >"$pkg/run.go" <<EOF
package $pkg

import (
	"fmt"
	"strconv"

	"$module/registry"
)

func init() {
	registry.Register($n, func(input string) (string, error) {
		target, err := strconv.Atoi(input)
		if err != nil {
			return "", fmt.Errorf("invalid limit: %w", err)
		}
		return strconv.FormatUint(Solve(target), 10), nil
	})
}
EOF
	echo "created $pkg/"
fi

# Verify each package registers the number matching its directory name.
bad=0
dirs=()
for d in p[0-9][0-9][0-9]; do
	[[ -d $d ]] || continue
	dirs+=("$d")
	want=$((10#${d#p}))
	got=$(grep -oP 'registry\.Register\(\s*\K[0-9]+' "$d"/*.go 2>/dev/null | cut -d: -f2 || true)
	if [[ -z $got ]]; then
		echo "warning: $d never calls registry.Register" >&2
		bad=1
	elif [[ $got != "$want" ]]; then
		echo "warning: $d registers problem(s) $(echo $got) but should register $want" >&2
		bad=1
	fi
done

{
	echo "package main"
	echo
	echo "// Each problem package registers itself in its init(); import new ones here."
	echo "// Generated by newprob.sh from the pNNN directories."
	echo "import ("
	for d in "${dirs[@]}"; do
		printf '\t_ "%s/%s"\n' "$module" "$d"
	done
	echo ")"
} >problems.go

gofmt -l . | grep -q . && gofmt -w .
go build ./...
echo "problems.go registers ${#dirs[@]} problem(s)"
exit $bad
