package main

// Each problem package registers itself in its init(); import new ones here.
// Generated by newprob.sh from the pNNN directories.
import (
	_ "github.com/brinwiththevlin/project_euler/p001"
	_ "github.com/brinwiththevlin/project_euler/p002"
	_ "github.com/brinwiththevlin/project_euler/p062"
)
